version: '3.8'
services:
    jupyter:
        container_name: jupyter-notebook
        # image: dptsi/php-web-dev:5.6
        image: jupyter/scipy-notebook:latest
        volumes:
            - .:/home/jovyan
        ports:
        - 8888:8888
        environment:
        - PASSWORD=password

